### ISSUE TITLE
Disappearing Thumbnail

### ISSUE THREAD

**Issue by egray523** [SSHOC/sshoc-marketplace-backend#437] opened 2024-02-01 15:35 UTC
I've noticed a repeating issue, where thumbnails will disappear from resources in the MP - I know this because I try to keep up to date on the DARIAH-FR resources that appear in the DARIAH Tools& Services Catalogue. Indeed,  I can nearly swear that I have done this in the past for DARIAH-FR resources (so that our T&S Catalogue can be beautiful).

In this case, it is :

PACTOLS (MP link: https://marketplace.sshopencloud.eu/tool-or-service/XBV3Uh/history)

Conservatoire 3D (MP link: https://marketplace.sshopencloud.eu/tool-or-service/MVnVXH/history)

Research has shown that there are indeed older versions with thumbnails, but I can't imagine Sarah or myself having willingly chosen to delete thumbnails when making other updates.

**Comment by egray523** [comment] 2024-02-29 15:38
Dear all,

I have some more feedback - I think I found the issue! 

Indeed, as I mentioned in the slack, in adding this new publication (https://marketplace.sshopencloud.eu/publication/zDXc4v) the user suggests a thumbnail, it loads, she submits, I approve it, and it disappears. occurance at 1624 (ish) & 1627 on 29th of February. ANd again, when I put the Celluloid entry up to date by connecting it with Peertube (https://marketplace.sshopencloud.eu/tool-or-service/EgS5M5) around 16:30, it disappeared again 

I believe the behavior is related to the changing versions - if the most recent accepted version (aka,t he one I approve as moderator) has it, it works. otherwise, it falls through the cracks and disappears.

**Comment by tparkola** [comment] 2024-08-30 15:20
@mkrzmr I think that what you found is not a bug as the draft items are in the users account (in his/her "My draft items" section) and not visible to other users. This is his/her draft, so it is related to this particular account. 

@egray523 I think I fixed this bug, once the changes are merged please test if it is indeed fixed :)

**Comment by laureD19** [comment] 2024-09-05 13:48
We tested with Ed on stage, the following behaviour: 

1. add a thumbnail to an item & publish (on stage tool-or-service/6Esznt)
2. create a relation to this item in another one & publish (stage tool-or-service/p1fAm1)
3. This results in the disappearing thumbnail added at step 1

**Comment by laureD19** [comment] 2024-09-05 13:50
2nd use case:

1. add a thumbnail to an item & publish (on stage tool-or-service/6Esznt)
2. delete an existing relation to this item in another one & publish (stage tool-or-service/p1fAm1)
3. This results in the disappearing thumbnail added at step 1

**Comment by tparkola** [comment] 2024-09-06 04:36
@laureD19 but from what I see the changes are not merged yet (my merge request is still open). So you need to wait for it to be merged and deployed on relevant environment by @mkrzmr or @KlausIllmayer and then test. Sorry I was not clear about that.

**Comment by KlausIllmayer** [comment] 2024-09-06 14:33
Currently blocked by https://github.com/SSHOC/sshoc-marketplace-backend/pull/457#issuecomment-2334027658

**Comment by KlausIllmayer** [comment] 2024-09-08 19:12
Fixed the previos block but run into a new block: https://github.com/SSHOC/sshoc-marketplace-backend/pull/458#issuecomment-2336792856

**Closed** 2024-09-08 22:20 UTC
Labels: bug, in review

**Comment by KlausIllmayer** [comment] 2024-09-08 22:29
Fixed also the last block and deployed the latest merge request. @laureD19 please try again on stage, now it should be the latest state.

**Comment by tparkola** [comment] 2024-09-09 05:39
@KlausIllmayer if needed I think you could merge this change without merging changes from #457.

**Comment by laureD19** [comment] 2024-09-09 08:59
excellent! It seems to work pretty well on stage now!!
Can you push it to production too @KlausIllmayer or are there any blockers?

**Comment by KlausIllmayer** [comment] 2024-09-09 09:18
these are the blockers for production: https://github.com/SSHOC/sshoc-marketplace-backend/issues/460 and https://github.com/SSHOC/sshoc-marketplace-backend/issues/461 - due to the big changes (upgrade to a new java version) it would be good to test stage very good before we go to production. also we will need to be very careful when doing the upgrade, as there are some manual tasks to be done (delete solr configuration) due to changes in the solr scheme.

**Comment by tparkola** [comment] 2024-09-13 18:59
I responded to both indicated issues. Please @KlausIllmayer have a look.

**Comment by KlausIllmayer** [comment] 2024-09-16 13:18
Thanks @tparkola - the blockers are gone, and even better, Tomasz did some great optimisation of the Solr re-index, which now instead of 3 hours just take around 5 minutes! That is really a great change, thanks a lot!

@mkrzmr @laureD19 If it is okay for you, I will do the update for production on Wednesday. It would be great, if until then you may find time to test the stage instance as there were many changes. Maybe create some items, test if moderation works and other stuff that come into your mind.

**Comment by laureD19** [comment] 2024-09-17 14:54
everything seems to work well on stage. I was able to add thumbnails and relations, delete relations, save... without encountering a new case of disappearing thumbnails. 

One side comment: on stage although some items do have media already, they are not displayed on the front-end: try NmPb2Z via the API and via the front-end for ex. 

Another side-comment: from 3h to 5min re-indexing!!! Amazing!! Thanks a lot :)

**Comment by KlausIllmayer** [comment] 2024-09-18 19:51
production updated, please try if it works there.
regarding stage and media: this is because i didn't copied all files from production. will solve this issue next week.

**Comment by laureD19** [comment] 2024-09-19 07:50
seems to work just fine :) Many thanks! 
And cool for next re. the media on stage.
