### ISSUE TITLE
Submitted items do not appear in moderation queue

### ISSUE THREAD

**Issue by mkrzmr** [SSHOC/sshoc-marketplace-backend#477] opened 2024-10-18 07:57 UTC
To reproduce:

Submit item to moderation queue with role contributor
Check moderation queue as moderator
The item does not show
api request 
https://marketplace-api.sshopencloud.eu/api/item-search?page=1&order=modified-on&d.status=SUGGESTED returns 0 hits

Critical, as new items cannot be approved via the ui anymore

**Comment by laureD19** [comment] 2024-10-18 08:03
just reproduced on the stage instance. Indeed...
Do you see anything in the database, though, based on the timestamps activities?

**Comment by stefanprobst** [comment] 2024-10-18 08:37
can you please check whether this is a backend of frontend issue (because i did update the frontend node.js version yesterday)

**Comment by KlausIllmayer** [comment] 2024-10-18 12:00
It is a combination of frontend changes and backend behavior. You can see in the frontend-url that you sent, that since the last update of frontend the field `d.conflict-at-source` is taken into account. It is set here as false but it seems, that this is not the correct value. Because if you run the API call without this parameter `api/item-search?page=1&order=modified-on&d.status=suggested` you will see all of the suggested items. And I think I know, why this is happening, because most of the items do not have set the property `conflict-at-source` and when asking for `false` it will look for items that do have set the property but with the value false. We introduced this the last days as it is necessary for the management of the ingested items.

@stefanprobst if it is possible to change the current behaviour, so that instead of setting it to `false` when the checkbox is not activated, that the reference to `d.conflict-at-source=false` is not applied to the parameters?

**Comment by stefanprobst** [comment] 2024-10-18 12:08
> if it is possible to change the current behavior, so that instead of setting it to false when the checkbox is not activated the reference to d.conflict-at-source=false is not applied to the parameters?

yes - although the current behavior is modeled after `d.deprecated-at-source` - i think at some point we should align these.

**Comment by stefanprobst** [comment] 2024-10-18 12:53
can you try again please?

fixed by (hopefully) https://github.com/SSHOC/sshoc-marketplace-frontend/commit/c082e1f6ebc9baf3a67c67ba4e683a5c88ff3a23

**Comment by stefanprobst** [comment] 2024-10-18 13:40
what page are we talking about here? `/moderate-items`?

**Comment by stefanprobst** [comment] 2024-10-18 14:04
misunderstood my own code from the past :) please try again.

**Closed** 2024-10-18 14:07 UTC
Labels: bug, critical
